#spring.datasource.url=jdbc://localhost:6060/javabatch

#spring.datasource.username=root 

#spring.datasource.password=Temp1234
#spring.jpa.hibernate.ddl-auto=create

spring:
 datasource:
  url: jdbc:mysql://localhost:6060/javabatch
  username: root
  password: Temp1234
 jpa:
  hibernate:
   ddl-auto: create
  show-sql: true
  properties:
   hibernate:
   formate_sql: true
   
